### ISSUE TITLE
Redefinition of builtin functions

### ISSUE THREAD

**Issue by Huy-Ngo** [dinhanhx/DSP-py-lib#4]
Some variable names or functions collides with builtin functions name, for example here:

https://github.com/dinhanhx/DSP-py-lib/blob/2b95de6952a8be55ff85afe4f51964fbc9941b6e/dsp_py/Fourier.py#L3

The function `range()` is a builtin Python function. This is not good and it should be replaced with some other words.

**Comment by dinhanhx** [comment]
What the word I can replace `range`? Should I use `interval`?

**Comment by Huy-Ngo** [comment]
Interval is fine. It's also more correct mathematically, since ["range" in maths](https://en.wikipedia.org/wiki/Range_(mathematics)) refers to the codomain of the function.

**Comment by dinhanhx** [comment]
I will do that right now

**Comment by dinhanhx** [comment]
[Solved](https://github.com/dinhanhx/DSP-py-lib/commit/bb63dfd51a924c0632594a472cd5bad72899fb06)
