### ISSUE TITLE
Apply PEP standards to code

### ISSUE THREAD

**Issue by Huy-Ngo** [dinhanhx/DSP-py-lib#5]
The current code base doesn't follow [PEP](https://www.python.org/dev/peps/), which is a good practice for formatting Python code.

Here are a few changes I would like to give:
- Use docstring instead of comments. (PEP 257)
- Use 2 empty lines between functions and no more than 1 within a function. (PEP 8)
- Modules should have short, all-lowercase names. (PEP 8)
- Function names should be lowercase, with words separated by underscores as necessary to improve readability. (PEP 8)

**Comment by dinhanhx** [comment]
I am too busy to change or switch to new format

**Comment by Huy-Ngo** [comment]
Can I do that in a PR or do you prefer your own styling convention?

**Comment by dinhanhx** [comment]
I guess you can do that in a PR if you have time. If then, I will change to new styling -> new features will be created more slowly
