### ISSUE TITLE
Union with the same library of other languages

### ISSUE THREAD

**Issue by Huy-Ngo** [dinhanhx/DSP-py-lib#6]
As I can see, this project emerged from it's [matlab sibling](https://github.com/dinhanhx/DSP-matlab-lib/) and you're considering implementation for R as well. Can you consider uniting them into one single repository instead of separate ones, so that it's easier to track the library in each language.

**Comment by dinhanhx** [comment]
How to do that? I am still new with multiple languages in a same repos.

**Comment by dinhanhx** [comment]
Well I decided to not implement this things for R due to USTH works and great decrease in demands.

**Comment by Huy-Ngo** [comment]
Well, then maybe it's not a good idea to merge. I'm closing this issue then.

**Comment by dinhanhx** [comment]
Agree
